#!/bin/bash
# Copyright (C) Made.com Tech Team 2016  coders@made.com  http://www.made.com
#
# Author  Kevin Sandom <kevin.sandom@made.com>
# Date    2016-05-27
# Origin  https://github.com/madedotcom/gls/blob/master/prototypes/bash/install
# Repo    git@github.com:madedotcom/gls.git
# Branch  master
# File    install
#
# Purpose Installs gls into the user's home directory.

mkdir -p ~/bin
cd ~/bin
ln -s ~-/gls .
